name: Angular CI/CD

on:
  push:
    branches: [main]  # אפשר לשנות ל־dev לפי הצורך
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular App
        run: npm run build -- --configuration=production

      # כאן את יכולה להוסיף שלב דיפלוי בהתאם לשרת שלך:
      # לדוגמה: העלאה ל־Firebase
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
